/**
 * Turns the TS token tree into CSS custom properties.
 *
 * There is one source of truth (the TS constants) and the stylesheet is
 * generated from it, so the two can never drift. `pnpm --filter
 * @pristine/tokens build` writes the result to `dist/tokens.css`, and a test
 * asserts the committed CSS matches what this produces.
 */
import { color } from './color.js';
import { typography } from './typography.js';
import { radius } from './radius.js';
import { space, layout } from './spacing.js';
import { borderWidth } from './border.js';
import { shadow, scrim } from './shadow.js';
import { duration, easing } from './motion.js';

export const CSS_VAR_PREFIX = 'pr';

/** camelCase and numeric keys to kebab-case var name segments. */
const kebab = (key: string): string =>
  key
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();

type TokenValue = string | number;
type TokenTree = { readonly [key: string]: TokenValue | TokenTree };

const isTokenTree = (value: TokenValue | TokenTree): value is TokenTree =>
  typeof value === 'object' && value !== null;

/**
 * Sizes are authored as unitless numbers so they stay usable in arithmetic on
 * the TS side. Anything that lands in CSS as a length needs px appended;
 * weights, line heights and durations do not.
 */
const withUnit = (path: readonly string[], value: TokenValue): string => {
  if (typeof value === 'string') return value;
  const group = path.join('-');
  if (group.startsWith('line-height')) return String(value);
  if (group.startsWith('font-weight')) return String(value);
  if (group.startsWith('duration')) return `${value}ms`;
  return `${value}px`;
};

function flatten(
  tree: TokenTree,
  path: readonly string[],
  out: Map<string, string>,
): Map<string, string> {
  for (const [key, value] of Object.entries(tree)) {
    const next = [...path, kebab(key)];
    if (isTokenTree(value)) {
      flatten(value, next, out);
      continue;
    }
    out.set(`--${CSS_VAR_PREFIX}-${next.join('-')}`, withUnit(next, value));
  }
  return out;
}

/** The full token tree, in the shape the CSS variable names follow. */
export const tokenTree = {
  color,
  font: {
    family: typography.fontFamily,
    size: typography.fontSize,
    weight: typography.fontWeight,
  },
  'line-height': typography.lineHeight,
  'letter-spacing': typography.letterSpacing,
  radius,
  space,
  layout,
  border: { width: borderWidth },
  shadow,
  scrim,
  duration,
  easing,
} as const satisfies TokenTree;

/** Every token as a `--pr-*` name to value pair. */
export function toCssVariables(): Map<string, string> {
  return flatten(tokenTree, [], new Map());
}

/** The generated stylesheet body, ready to write to disk. */
export function toCssText(): string {
  const lines = [...toCssVariables()].map(([name, value]) => `  ${name}: ${value};`);
  return [
    '/*',
    ' * Generated by @pristine/tokens. Do not edit by hand.',
    ' * Run `pnpm --filter @pristine/tokens build` after changing src/.',
    ' */',
    '',
    ':root {',
    ...lines,
    '}',
    '',
  ].join('\n');
}
